# Site settings
title: Dillon Pittman
description: Portfolio
# baseurl: "/particle" # the subpath of your site, e.g. /blog
url: "localhost:3000" # the base hostname & protocol for your site e.g. http://willianjusten.com.br

# User settings
username: Dillon Pittman
user_description: Experienced problem solver new to development, eager to learn, and have fun while doing it. I’ve updated my toolbox and now I’m seeking entry level opportunities.
user_title: Full Stack Developer
email: pittmanwdillon@gmail.com
linkedin_username: Dillon Pittman
github_username: DillonPittman
gplus_username: lorem_ipsum

# Google-analytics
google-analytics:
  id: ""

exclude: ["package.json", "src", "node_modules"]
